# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- beta


steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/frontend/'
    azureSubscription: 'CC-PAYG-01(4073f0a2-5031-4a64-9e92-81d19c5676f3)'
    Destination: 'AzureBlob'
    storage: 'wemkbetasa'
    ContainerName: '$web'